exports.orders = {
	Magnoliales : "Magnoliaceae Winteraceae Himantandraceae Cannellaceae Annonaceae Myristicaceae Degeneriaceae",
	Illiciales : "Illiciaceae Schisandraceae",
	Laurales : "Austrobaileyaceae Lactoridaceae Eupomatiaceae Gomortegaceae Monimiaceae Calycanthaceae Chloranthaceae Lauraceae Hernandiaceae",
	Piperales : "Piperaceae Saururaceae Peperomiaceae",
	Aristolochiales : "Aristolochiaceae Nepenthaceae",
	Nymphaeales : "Ceratophyllaceae Nymphaeaceae",
	Ranunculales : "Berberidaceae Ranunculaceae Lardizabalaceae Menispermaceae",
	Papaverales : "Papaveraceae Fumariaceae",
	Sarraceniales : "Sarraceniaceae",
	Trochodendrales : "Trochodendraceae",
	Hamamelidales : "Cercidiphyllaceae Platanaceae Hamamelidaceae",
	Eucommiales : "Eucommiaceae",
	Leitneriales : "Leitneriaceae",
	Myricales : "Myricaceae",
	Fagales : "Betulaceae Fagaceae Balanopaceae",
	Casuarinales : "Casuarinaceae",
	Caryophyllales : "Cactaceae Aizoaceae Caryophyllaceae Nyctaginaceae Amaranthaceae Phytolaccaceae Chenopodiaceae Didiereaceae Portulacaceae Basellaceae",
	Batales : "Batidaceae",
	Polygonales : "Polygonaceae",
	Plumbaginales : "Plumbaginaceae",
	Dilleniales : "Dilleniaceae Paeoniaceae Crossosomataceae",
	Theales : "Theaceae Ochnaceae Dipterocarpaceae Clusiaceae Elatinaceae Quiinaceae Marcgraviaceae",
	Malvales : "Scytopetalaceae Elaeocarpaceae Tiliaceae Sterculiaceae Bombacaceae Malvaceae Sphaerosepalaceae Sarcolaenaceae",
	Urticales : "Ulmaceae Moraceae Urticaceae",
	Lecythidales : "Lecythidaceae",
	Violales : "Violaceae Flacourtiaceae Lacistemataceae Passifloraceae Turneraceae Malesherbiaceae Fouquieriaceae Caricaceae Bixaceae Cochlospermaceae Cistaceae Tamaricaceae Ancistrocladaceae Frankeniaceae Achariaceae Begoniaceae Loasaceae Datiscaceae Cucurbitaceae",
	Salicales : "Salicaceae",
	Capparales : "Capparaceae Tovariaceae Brassicaceae Resedaceae Moringaceae",
	Ericales : "Clethraceae Grubbiaceae Cyrillaceae Ericaceae Epacridaceae Empetraceae Pyrolaceae",
	Diapensales : "Diapensiaceae",
	Ebenales : "Sapotaceae Ebenaceae Styracaceae",
	Primulales : "Primulaceae Myrsinaceae",
	Rosales : "Cunoniaceae Pittosporaceae Droseraceae Brunelliaceae Eucryphiaceae Bruniaceae Rosaceae Crassulaceae Cephalotaceae Chrosobalanaceae",
	Fabales : "Papilionaceae Caesalpiniaceae Mimosaceae",
	Podostemales : "Podostemaceae",
	Haloragales : "Theligonaceae Haloragaceae Hippuridaceae",
	Myrtales : "Sonneratiaceae Trapaceae Lythraceae Rhizophoraceae Penaeaceae Thymelaeaceae Myrtaceae Punicaceae Onagraceae Oliniaceae Melastomataceae Combretaceae",
	Cornales : "Nyssaceae Garryaceae Alangiaceae Cornaceae",
	Proteales : "Elaeagnaceae Protaceae",
	Santales : "Santalaceae Medusandraceae Olacaceae Loranthaceae Misodendraceae Cynomoriaceae Balanophoraceae",
	Rafflesiales : "Rafflesiaceae Hydnoraceae",
	Celastrales : "Geissolomataceae Celastraceae Stackhousiaceae Salvadoraceae Corynocarpaceae Icacinaceae Aquifoliaceae Dichapetalaceae",
	Euphorbiales : "Buxaceae Pandaceae Euphorbiaceae",
	Rhamnales : "Rhamnaceae Vitaceae",
	Sapindales : "Staphyleaceae Melianthaceae Connaraceae Sapindaceae Sabiaceae Julianiaceae Hippocastanaceae Aceraceae Burseraceae Anacardiaceae Simaroubaceae Coriariaceae Meliaceae Cneoraceae Rutaceae Zygophyllaceae",
	Juglandales : "Juglandaceae",
	Geraniales : "Houmiriaceae Linaceae Geraniaceae Oxalidaceae Erythroxylaceae Limnanthaceae Balsaminaceae Tropaeolaceae",
	Polygalales : "Malphighiaceae Trigoniaceae Tremandraceae Vochysiaceae Polygalaceae Krameriaceae",
	Umbellales : "Araliaceae Apiaceae",
	Gentianales : "Loganiaceae Gentianaceae Apocynaceae Asclepiadaceae Oleaceae",
	Polemoniales : "Nolanaceae Solanaceae Convolvulaceae Menyanthaceae Lennoaceae Polemoniaceae Ehretiaceae Hydrophyllaceae Boraginaceae",
	Lamiales : "Verbenaceae Lamiaceae Tetrachondraceae Callitrichaceae Phrymaceae",
	Plantaginales : "Plantaginaceae",
	Scrophulariales : "Columelliaceae Myoporaceae Scrophulariaceae Globulariaceae Gesneriaceae Orobanchaceae Bignoniaceae Acanthaceae Pedaliaceae Hydrostachydaceae Martyniaceae Lentibulariaceae",
	Campanulales : "Campanulaceae Lobeliaceae Stylidiaceae Brunoniaceae Goodeniaceae",
	Rubiales : "Rubiaceae",
	Dipsacales : "Adoxaceae Caprifoliaceae Valerianaceae Dipsacaceae Calyceraceae",
	Asterales : "Asteraceae",
	Alismatales : "Butomaceae Limnocharitaceae Alismataceae",
	Hydrocharitales : "Hydrocharitaceae",
	Najadales : "Aponogetonaceae Scheuchzeriaceae Juncaginaceae Lilaeaceae Najadaceae Potamogetonaceae Zannichelliaceae Ruppiaceae Zosteraceae Posidoniaceae Cymodoceaceae",
	Triuridales : "Triuridaceae",
	Commelinales : "Xyridaceae Rapateaceae Mayacaceae Commelinaceae",
	Eriocaulales : "Eriocaulaceae",
	Restionales : "Flagellariaceae Centrolepidaceae Restionaceae",
	Poales : "Poaceae",
	Juncales : "Juncaceae Thurniaceae",
	Cyperales : "Cyperaceae",
	Typhales : "Typhaceae Sparganiaceae",
	Bromeliales : "Bromeliaceae",
	Zingiberales : "Musaceae Strelitziaceae Zingiberaceae Cannaceae Marantaceae",
	Arecales : "Arecaceae",
	Cyclanthales : "Cyclanthaceae",
	Pandanales : "Pandanaceae",
	Arales : "Lemnaceae Araceae",
	Liliales : "Pontederiaceae Philydraceae Iridaceae Liliaceae Amaryllidaceae Agavaceae Xanthorrhoeaceae Velloziaceae Haemodoraceae Taccaceae Stemonaceae Smilacaceae Dioscoreaceae",
	Orchidales : "Burmanniaceae Orchidaceae"
}; 